services:
  database-mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_DATABASE: todo_app_db
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

networks:
  my_network:
    driver: bridge

# docker-compose up -d
